models/Trip.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%trip}}".
 *
 * @property integer $id
 * @property integer $from_city
 * @property string $from_date
 * @property string $from_time
 * @property string $from_info
 * @property integer $to_city
 * @property string $to_date
 * @property string $to_time
 * @property string $to_info
 * @property string $info
 * @property double $price
 * @property integer $bus_id
 */
class Trip extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%trip}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['from_city', 'from_date', 'from_time', 'from_info', 'to_city', 'to_date', 'to_time', 'to_info', 'info', 'price', 'bus_id'], 'required'],
            [['from_city', 'to_city', 'bus_id', ], 'integer'],
            [['from_date', 'from_time', 'to_date', 'to_time', ], 'safe'],
            [['price'], 'number'],
            [['from_info', 'to_info', 'info'], 'string', 'max' => 256]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', '#'),
            'from_city' => Yii::t('app', 'Город отправления'),
            'from_date' => Yii::t('app', 'Дата отправления'),
            'from_time' => Yii::t('app', 'Время отправления'),
            'from_info' => Yii::t('app', 'Место отправления '),
            'to_city' => Yii::t('app', 'Город прибытия'),
            'to_date' => Yii::t('app', 'Дата прибытия'),
            'to_time' => Yii::t('app', 'Время прибытия'),
            'to_info' => Yii::t('app', 'Место прибытия'),
            'info' => Yii::t('app', 'Детальное описание'),
            'price' => Yii::t('app', 'Цена'),
            'bus_id' => Yii::t('app', '# автобуса'),
        ];
    }

    public function cityName($city_id) {
        $city = City::find()
            ->where(['id' => $city_id])
            ->one();
        if (isset( $city )) {
            return $city->name;
        } else {
            return "";
        }
    }

    public static function cityList() {
        $cities = City::find()->all();
        return ArrayHelper::map($cities, 'id', 'name');
    }

    public function getAllReservations()
    {
        $list = Reservation::find()
            ->where(['trip_id' => $this->id])
            ->all();
        return $list;
    }

    public function getReservationsCount() {
        $list = $this->getAllReservations();
        if($list){
            return count($list);
        }else{
            return 0;
        }
    }

    /**
     * @inheritdoc
     * @return TripQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TripQuery(get_called_class());
    }
}

controllers/ReservationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Reservation;
use app\models\ReservationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\filters\AccessControl;

/**
 * ReservationController implements the CRUD actions for Reservation model.
 */
class ReservationController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','view','create','update','delete'],
                'rules' => [
                    [
                        'allow' => false,
                        'actions' => [],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index','view','create','update','delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reservation models.
     * @return mixed
     */
    public function actionIndex($trip_id=null, $trip_id_clear=null)
    {
        if(isset($trip_id)){
            $_SESSION['trip_id']=$trip_id;
        }

        if(isset($trip_id_clear)){
            unset($_SESSION['trip_id']);
        }

        $searchModel = new ReservationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if(isset($_SESSION['trip_id'])) {
            $dataProvider->query->andFilterWhere([
                'trip_id' => $_SESSION['trip_id'],
            ]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Reservation model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Reservation model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Reservation();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Reservation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Reservation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Reservation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Reservation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Reservation::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/TripController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Trip;
use app\models\TripSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;

//Note: install datePicker : http://www.yiiframework.com/forum/index.php/topic/63270-class-yiijuidatepicker-not-found/

/**
 * TripController implements the CRUD actions for Trip model.
 */

class TripController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','view','create','update','delete'],
                'rules' => [
                    [
                        'allow' => false,
                        'actions' => [],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index','view','create','update','delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Trip models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TripSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Trip model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Trip model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Trip();

        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Trip model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Trip model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if(Trip::findOne($id)->getReservationsCount()>0){
            throw new ForbiddenHttpException('This trip includes a reservation!');
        }

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Trip model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Trip the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Trip::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/trip/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\City;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Trip */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="trip-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php $cities = City::find()->all();
        $items = ArrayHelper::map($cities,'id','name');
        echo $form->field($model, 'from_city')->dropDownList($items); ?>

    <?= $form->field($model, 'from_date')->widget(DatePicker::classname(), [
        'language' => 'ru',
        'dateFormat' => 'yyyy-MM-dd',
    ]) ?>

    <?= $form->field($model, 'from_time')->textInput() ?>

    <?= $form->field($model, 'from_info')->textInput(['maxlength' => true]) ?>

    <?php $cities = City::find()->all();
        $items = ArrayHelper::map($cities,'id','name');
        echo $form->field($model, 'to_city')->dropDownList($items); ?>

    <?= $form->field($model, 'to_date')->widget(DatePicker::classname(), [
        'language' => 'ru',
        'dateFormat' => 'yyyy-MM-dd',
    ]) ?>

    <?= $form->field($model, 'to_time')->textInput() ?>

    <?= $form->field($model, 'to_info')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'info')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput() ?>

    <?= $form->field($model, 'bus_id')->dropDownList([ '8' => 'На 8 мест', '14' => 'На 14 мест', '15' => 'На 15 мест', '18' => 'На 18 мест', '21' => 'На 21 мест']); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/trip/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TripSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="trip-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'from_city') ?>

    <?= $form->field($model, 'from_date') ?>

    <?= $form->field($model, 'from_time') ?>

    <?= $form->field($model, 'from_info') ?>

    <?= $form->field($model, 'to_city') ?>

    <?php // echo $form->field($model, 'to_date') ?>

    <?php // echo $form->field($model, 'to_time') ?>

    <?php // echo $form->field($model, 'to_info') ?>

    <?php // echo $form->field($model, 'info') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'bus_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/trip/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Trip */

$this->title = Yii::t('app', 'Create Trip');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trips'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="trip-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/trip/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\Trip;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TripSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Trips');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="trip-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Trip'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute'=>'id',
                'options' => ['width' => '42']
            ],
            [
                'attribute'=>'id',
                'options' => ['width' => '42']
            ],
            [
                'attribute'=>'from_city',
                'format'=>'text',
                'content'=>function($data){
                    return $data->cityName($data->from_city);
                },
                'filter' => Trip::cityList()
            ],
            'from_date',
            'from_time',
            // 'from_info',
            [
                'attribute'=>'to_city',
                'format'=>'text',
                'content'=>function($data){
                    return $data->cityName($data->to_city);
                },
                'filter' => Trip::cityList()
            ],
            'to_date',
            'to_time',
            // 'to_info',
            // 'info',
            // 'price',
            'bus_id',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete} {link}',
                'buttons' => [
                    'link' => function ($url,$model,$key) {
                        return Html::a('Бронь('.$model->getReservationsCount().')', Url::to(['reservation/index', 'trip_id' => $model->id]));
                    },
                ],
            ],
        ],
    ]); ?>

</div>

views/trip/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Trip */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Trip',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trips'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="trip-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/trip/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Trip */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trips'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="trip-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'from_city',
            'from_date',
            'from_time',
            'from_info',
            'to_city',
            'to_date',
            'to_time',
            'to_info',
            'info',
            'price',
            'bus_id',
        ],
    ]) ?>

</div>